name: Netlify Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    - name: Deploy production to Netlify
      run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
